version: "3.9"
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    working_dir: /var/www
    links:
      - mysql
    volumes:
      - ./../:/var/www
    command: php -S 0.0.0.0:80 -t .
    ports:
      - "80:80"
